# Generated by Django 3.0.8 on 2020-07-31 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ksywka')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Imię')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nazwisko')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Parę słów o sobie')),
                ('year_of_birth', models.IntegerField(blank=True, null=True, verbose_name='Data urodzenia')),
                ('in_academy_since', models.IntegerField(blank=True, null=True, verbose_name='W akademi od')),
                ('role', models.IntegerField(choices=[(1, 'Coach'), (2, 'Staff'), (3, 'Player'), (4, 'Fan')], default=4, verbose_name='Rola')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='Wynagrodzenie za godzinę')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
