# Generated by Django 3.0.8 on 2020-07-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.ManyToManyField(blank=True, null=True, through='Academy.TeamCoaches', to='Academy.Coach', verbose_name='Trener'),
        ),
    ]
