# Generated by Django 3.0.8 on 2020-07-31 21:48

import Academy.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='favourite_number',
            field=models.IntegerField(blank=True, null=True, validators=[Academy.validators.number_on_tshirt], verbose_name='Preferowany numer na koszulce'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.IntegerField(blank=True, choices=[(1, 'Bez pozycji'), (2, 'Bramkarz'), (3, 'Obrońca'), (4, 'Pomocnik'), (5, 'Napastnik')], null=True, verbose_name='Pozycja na boisku'),
        ),
        migrations.AlterField(
            model_name='player',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, 'Chłopiec'), (2, 'Dziewczynka')], null=True, verbose_name='Płeć'),
        ),
    ]
