# Generated by Django 3.0.8 on 2020-08-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0002_auto_20200731_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='favourite_players',
            field=models.ManyToManyField(blank=True, null=True, to='Academy.Player', verbose_name='Ulubieni gracze'),
        ),
        migrations.AlterField(
            model_name='fan',
            name='favourite_teams',
            field=models.ManyToManyField(blank=True, null=True, to='Academy.Team', verbose_name='Ulubione zespoły'),
        ),
    ]
